#!/bin/bash
#Examples for running psweep2

NGPU=$1
NWORKERS=$((3*$NGPU))
NRANKS=$((1+$NWORKERS))

echo "Starting with $NWORKERS workers and $NRANKS ranks"

#export CUDA_VISIBLE_DEVICES="0,1"
export CUDA_VISIBLE_DEVICES="GPU-dce812e3-d9fa-34c1-d3e9-44478ff8f5e7,GPU-763f0b04-2db4-6f01-2a2f-596c8358fbc7"

NCHAINS=50
MAXGEN=100000
STATEFILE=psweepdreamABCz.state
MINMAXFILE=testabc_minmax.bounds
OBSFILE=testabc_observ.data
EPSILFILE=testabc.epsilons
DIR=testabcdir
SEARCHTYPE=DREAM-ABCz
WORKSCRIPT=../configs/test_abc_twopeak_gpu.cfg

#HOSTFILE=/nfs-mirror/gpumachinefile

stdo=stdout_psweepABCz
stde=stderr_psweepABCz

#nohup mpirun -n $NCHAINS ./test_psweep2_lib.exe -DIR $DIR -WORKSCRIPT $WORKSCRIPT -SEARCHTYPE $SEARCHTYPE -VARIABLES $MINMAXFILE -OBSERVATIONS $OBSFILE -EPSILONS $EPSILFILE -STATEFILE $STATEFILE -MAXGENS $MAXGEN -NCHAINS $NCHAINS 1>$stdo 2>$stde

#nohup mpirun -n 26 ./test_psweep2_lib.exe -DIR $DIR -WORKSCRIPT $WORKSCRIPT -SEARCHTYPE $SEARCHTYPE -VARIABLES $MINMAXFILE -OBSERVATIONS $OBSFILE -EPSILONS $EPSILFILE -STATEFILE $STATEFILE -MAXGENS $MAXGEN -NCHAINS $NCHAINS -TAG=ABCYOLO 1>$stdo 2>$stde &

#nohup mpirun -n $NRANKS --hostfile $HOSTFILE gputest.exe -DIR $DIR -WORKSCRIPT $WORKSCRIPT -SEARCHTYPE $SEARCHTYPE -VARIABLES $MINMAXFILE -OBSERVATIONS $OBSFILE -EPSILONS $EPSILFILE -STATEFILE $STATEFILE -MAXGENS $MAXGEN -NCHAINS $NCHAINS -TAG=ABCYOLO 1>$stdo 2>$stde &
nohup mpirun -n $NRANKS gputest.exe -DIR $DIR -WORKSCRIPT $WORKSCRIPT -SEARCHTYPE $SEARCHTYPE -VARIABLES $MINMAXFILE -OBSERVATIONS $OBSFILE -EPSILONS $EPSILFILE -STATEFILE $STATEFILE -MAXGENS $MAXGEN -NCHAINS $NCHAINS -TAG=ABCYOLO 1>$stdo 2>$stde &
